"""
Django settings for dripcheck_django project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
import dj_database_url
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1mjp(xv!pte5z=+0kasgl#7q^p4y9c5_=w5!(++p_*-)(gex#y'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'api',
    'accounts',
    'bundle_generate',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'dripcheck_django.middleware.RequestLoggingMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = True

ROOT_URLCONF = 'dripcheck_django.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dripcheck_django.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

#DATABASES = {
#    "default": dj_database_url.parse(os.getenv("DATABASE_URL", f"sqlite:///{BASE_DIR}/db.sqlite3"))
#}

DATABASES = {
    "default": dj_database_url.parse(os.getenv("DATABASE_URL"))
}
print("DATABASES",DATABASES)
# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Media files (User uploaded uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

AUTH_USER_MODEL = 'accounts.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
}

# Twilio API Settings
TWILIO_ACCOUNT_SID = config('TWILIO_ACCOUNT_SID', default='your_twilio_account_sid')
TWILIO_AUTH_TOKEN = config('TWILIO_AUTH_TOKEN', default='your_twilio_auth_token')
TWILIO_PHONE_NUMBER = config('TWILIO_PHONE_NUMBER', default='your_twilio_phone_number')

# Gemini API Settings
GEMINI_API_KEY = config('GEMINI_API_KEY')

# Hugging Face avatar generation settings
HF_API_TOKEN = config('HF_API_TOKEN', default='')
HF_MODEL_ID = config('HF_MODEL_ID', default='Qwen/Qwen-Image-Edit')
HF_GENERATION_BACKEND = config('HF_GENERATION_BACKEND', default='diffusers')

# ── Logging ───────────────────────────────────────────────────────────────────
# Routes all project loggers (api, services, engine, etc.) to the console.
# Django's default config only shows ERROR — this adds INFO and WARNING too.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,

    'formatters': {
        'verbose': {
            'format': '\033[36m{asctime}\033[0m \033[1m{levelname:<8}\033[0m \033[33m{name}\033[0m  {message}',
            'style': '{',
            'datefmt': '%H:%M:%S',
        },
        'simple': {
            'format': '{asctime} {levelname:<8} {name}  {message}',
            'style': '{',
            'datefmt': '%H:%M:%S',
        },
    },

    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
            'level': 'DEBUG',
        },
    },

    'loggers': {
        # ── Django internals ──────────────────────────────────────────────────
        'django': {
            'handlers': ['console'],
            'level': 'WARNING',       # Only show Django warnings/errors (not every ORM query)
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',         # Show 500s in the console
            'propagate': False,
        },

        # ── Our app modules ───────────────────────────────────────────────────
        'api': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'services': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'engine': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'accounts': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'bundle_generate': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'bundlegeneration': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'dripcheck_django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        # ── Frontend logs (from FrontendLogView) ──────────────────────────────
        'frontend': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        # ── Root fallback: catches anything not matched above ─────────────────
        '': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}
