# Generated by Django 6.0.5 on 2026-05-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceBundle',
            fields=[
                ('bundle_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('items', models.JSONField(default=list)),
                ('total_price', models.FloatField()),
                ('match_percentage', models.FloatField()),
                ('occasion_tags', models.JSONField(default=list)),
                ('style_tags', models.JSONField(default=list)),
                ('source', models.CharField(default='marketplace', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OutfitBundle',
            fields=[
                ('bundle_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=255)),
                ('items', models.JSONField(default=list)),
                ('compatibility_score', models.FloatField()),
                ('dominant_color', models.CharField(max_length=100)),
                ('dominant_palette', models.CharField(max_length=100)),
                ('occasion_tags', models.JSONField(default=list)),
                ('style_tags', models.JSONField(default=list)),
                ('mood_tags', models.JSONField(default=list)),
                ('is_saved', models.BooleanField(default=False)),
                ('wear_count', models.IntegerField(default=0)),
                ('source', models.CharField(choices=[('user_generated', 'User Generated'), ('marketplace_inspiration', 'Marketplace Inspiration')], max_length=50)),
                ('has_missing_item', models.BooleanField(blank=True, null=True)),
                ('created_at', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('skin_tone', models.CharField(max_length=100)),
                ('hair_color', models.CharField(max_length=100)),
                ('body_type', models.CharField(max_length=100)),
                ('daily_routines', models.JSONField(default=list)),
                ('occasion_frequency', models.JSONField(default=dict)),
                ('style_vibes', models.JSONField(default=list)),
                ('favorite_colors', models.JSONField(default=list)),
                ('avoided_colors', models.JSONField(default=list)),
                ('fit_preferences', models.JSONField(default=list)),
                ('material_sensitivity', models.JSONField(default=list)),
                ('pattern_preferences', models.JSONField(default=list)),
                ('onboarding_complete', models.BooleanField(default=False)),
                ('created_at', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WardrobeItem',
            fields=[
                ('item_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Top', 'Top'), ('Bottom', 'Bottom'), ('Footwear', 'Footwear'), ('Layer', 'Layer'), ('Accessory', 'Accessory')], max_length=50)),
                ('subcategory', models.CharField(max_length=100)),
                ('primary_color', models.CharField(max_length=100)),
                ('secondary_color', models.CharField(blank=True, max_length=100, null=True)),
                ('color_family', models.CharField(choices=[('Neutral', 'Neutral'), ('Earth', 'Earth'), ('Dark', 'Dark'), ('Bold', 'Bold'), ('Pastel', 'Pastel'), ('Warm', 'Warm')], max_length=50)),
                ('pattern', models.CharField(choices=[('Solid', 'Solid'), ('Stripes', 'Stripes'), ('Checks', 'Checks'), ('Graphic', 'Graphic'), ('Floral', 'Floral'), ('Abstract', 'Abstract')], max_length=50)),
                ('fit', models.CharField(choices=[('Slim', 'Slim'), ('Regular', 'Regular'), ('Relaxed', 'Relaxed'), ('Oversized', 'Oversized'), ('Cropped', 'Cropped'), ('Baggy', 'Baggy'), ('Tapered', 'Tapered')], max_length=50)),
                ('occasion_type', models.JSONField(default=list)),
                ('season', models.CharField(choices=[('Summer', 'Summer'), ('Winter', 'Winter'), ('Monsoon', 'Monsoon'), ('All-season', 'All-season')], max_length=50)),
                ('formality_level', models.IntegerField()),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('material', models.CharField(blank=True, max_length=100, null=True)),
                ('style_tags', models.JSONField(blank=True, null=True)),
                ('mood_tags', models.JSONField(blank=True, null=True)),
                ('aesthetic_tone', models.CharField(blank=True, max_length=255, null=True)),
                ('wear_count', models.IntegerField(default=0)),
                ('last_worn', models.CharField(blank=True, max_length=100, null=True)),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('added_at', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WearLog',
            fields=[
                ('log_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=255)),
                ('bundle_id', models.CharField(blank=True, max_length=255, null=True)),
                ('item_ids', models.JSONField(default=list)),
                ('occasion_tag', models.CharField(max_length=100)),
                ('worn_date', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
