# Generated by Django 6.0.5 on 2026-05-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wardrobeitem',
            name='ai_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wardrobeitem',
            name='fallback_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wardrobeitem',
            name='original_image',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='wardrobeitem',
            name='processed_image',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
