# Generated by Django 6.0.5 on 2026-05-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_wardrobeitem_ai_generated_wardrobeitem_fallback_used_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wardrobeitem',
            name='image_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
