# Generated by Django 6.0.6 on 2026-07-25 14:47

from django.db import migrations


def populate_users(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    
    models = ['UserProfile', 'WardrobeItem', 'OutfitBundle', 'WearLog']
    for model_name in models:
        Model = apps.get_model('api', model_name)
        for obj in Model.objects.all():
            if obj.old_user_id:
                try:
                    user = User.objects.get(mobile_no=obj.old_user_id)
                    obj.user = user
                    obj.save()
                except User.DoesNotExist:
                    pass

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_outfitbundle_user_id_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_users, reverse_code=migrations.RunPython.noop),
    ]
