# Generated by Django 6.0.6 on 2026-07-25 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_outfitbundle_old_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wardrobeitem',
            name='product_url',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
