# Generated by Django 6.0.6 on 2026-08-08 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_wardrobeitem_product_url'),
        ('bundle_generate', '0005_topwearairecommendation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('product', 'Product'), ('bundle', 'Bundle'), ('marketplace_bundle', 'Marketplace Bundle')], max_length=30)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('bundle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.outfitbundle')),
                ('marketplace_bundle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.marketplacebundle')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bundle_generate.merchantproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-added_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('bundle__isnull', True), ('item_type', 'product'), ('marketplace_bundle__isnull', True), ('product__isnull', False)), models.Q(('bundle__isnull', False), ('item_type', 'bundle'), ('marketplace_bundle__isnull', True), ('product__isnull', True)), models.Q(('bundle__isnull', True), ('item_type', 'marketplace_bundle'), ('marketplace_bundle__isnull', False), ('product__isnull', True)), _connector='OR'), name='wishlist_target_matches_type'), models.UniqueConstraint(fields=('user', 'item_type', 'product'), name='uniq_wishlist_user_product'), models.UniqueConstraint(fields=('user', 'item_type', 'bundle'), name='uniq_wishlist_user_bundle'), models.UniqueConstraint(fields=('user', 'item_type', 'marketplace_bundle'), name='uniq_wishlist_user_marketplace_bundle')],
            },
        ),
    ]
