# Generated by Django 6.0.7 on 2026-08-09 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_wardrobeitem_product_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('wishlist_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('product', 'Product'), ('bundle', 'Bundle')], max_length=20)),
                ('item_id', models.CharField(max_length=255)),
                ('item_data', models.JSONField(default=dict, help_text='Snapshot of the liked item at like-time')),
                ('created_at', models.CharField(max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'item_type', 'item_id'), name='unique_wishlist_item_per_user')],
            },
        ),
    ]
