# Generated by Django 6.0.7 on 2026-08-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_wishlistitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistitem',
            name='item_type',
            field=models.CharField(choices=[('product', 'Product'), ('wardrobe_item', 'Wardrobe Item'), ('bundle', 'Bundle'), ('marketplace_bundle', 'Marketplace Bundle'), ('ai_bundle', 'AI Bundle')], max_length=20),
        ),
    ]
