# Generated by Django 6.0.6 on 2026-08-08 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_wishlist'),
        ('bundle_generate', '0005_topwearairecommendation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='wishlist',
            name='wishlist_target_matches_type',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='ai_bundle_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='bundle_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='wardrobe_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.wardrobeitem'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='item_type',
            field=models.CharField(choices=[('product', 'Product'), ('wardrobe_item', 'Wardrobe Item'), ('bundle', 'Bundle'), ('marketplace_bundle', 'Marketplace Bundle'), ('ai_bundle', 'AI Bundle')], max_length=30),
        ),
        migrations.AddConstraint(
            model_name='wishlist',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('ai_bundle_id__isnull', True), ('bundle__isnull', True), ('item_type', 'product'), ('marketplace_bundle__isnull', True), ('product__isnull', False), ('wardrobe_item__isnull', True)), models.Q(('ai_bundle_id__isnull', True), ('bundle__isnull', True), ('item_type', 'wardrobe_item'), ('marketplace_bundle__isnull', True), ('product__isnull', True), ('wardrobe_item__isnull', False)), models.Q(('ai_bundle_id__isnull', True), ('bundle__isnull', False), ('item_type', 'bundle'), ('marketplace_bundle__isnull', True), ('product__isnull', True), ('wardrobe_item__isnull', True)), models.Q(('ai_bundle_id__isnull', True), ('bundle__isnull', True), ('item_type', 'marketplace_bundle'), ('marketplace_bundle__isnull', False), ('product__isnull', True), ('wardrobe_item__isnull', True)), models.Q(('ai_bundle_id__isnull', False), ('bundle__isnull', True), ('bundle_data__isnull', False), ('item_type', 'ai_bundle'), ('marketplace_bundle__isnull', True), ('product__isnull', True), ('wardrobe_item__isnull', True)), _connector='OR'), name='wishlist_target_matches_type'),
        ),
        migrations.AddConstraint(
            model_name='wishlist',
            constraint=models.UniqueConstraint(fields=('user', 'item_type', 'wardrobe_item'), name='uniq_wishlist_user_wardrobe_item'),
        ),
        migrations.AddConstraint(
            model_name='wishlist',
            constraint=models.UniqueConstraint(fields=('user', 'item_type', 'ai_bundle_id'), name='uniq_wishlist_user_ai_bundle'),
        ),
    ]
