# Generated by Django 6.0.7 on 2026-08-19
# Data migration: migrate legacy flat occasion tags to the hierarchical
# occasion taxonomy (services/occasion_taxonomy.py). Every legacy value maps
# to a parent + child pair:
#   Business  -> [Formal, Business]
#   Weekend   -> [Casual, Weekend]
#   Party     -> [Party & Nightlife, Party]
#   Gym       -> [Sports & Active, Gym]
#   Date Night-> [Date & Social, Date Night]
#   Casual/Formal stay as-is (parents).
# WearLog stores a single occasion value, so it keeps the child (Business,
# Party, Gym, Date Night, Weekend).

from django.db import migrations

from services.occasion_taxonomy import canonical_child, normalize_occasion_list


def _migrate_json_list(apps, schema_editor):
    WardrobeItem = apps.get_model('api', 'WardrobeItem')
    for item in WardrobeItem.objects.all():
        mapped = normalize_occasion_list(item.occasion_type or [])
        if mapped != item.occasion_type:
            item.occasion_type = mapped
            item.save(update_fields=['occasion_type'])


def _migrate_outfit_bundles(apps, schema_editor):
    OutfitBundle = apps.get_model('api', 'OutfitBundle')
    for bundle in OutfitBundle.objects.all():
        mapped = normalize_occasion_list(bundle.occasion_tags or [])
        if mapped != bundle.occasion_tags:
            bundle.occasion_tags = mapped
            bundle.save(update_fields=['occasion_tags'])


def _migrate_marketplace_bundles(apps, schema_editor):
    MarketplaceBundle = apps.get_model('api', 'MarketplaceBundle')
    for bundle in MarketplaceBundle.objects.all():
        mapped = normalize_occasion_list(bundle.occasion_tags or [])
        if mapped != bundle.occasion_tags:
            bundle.occasion_tags = mapped
            bundle.save(update_fields=['occasion_tags'])


def _migrate_wear_logs(apps, schema_editor):
    WearLog = apps.get_model('api', 'WearLog')
    for log in WearLog.objects.all():
        canonical = canonical_child(log.occasion_tag)
        if canonical and canonical != log.occasion_tag:
            log.occasion_tag = canonical
            log.save(update_fields=['occasion_tag'])


def _reverse(apps, schema_editor):
    # Intentionally irreversible: mapping back from a hierarchy to flat
    # legacy tags would lose the new parent/child information.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_wishlistitem_item_type'),
    ]

    operations = [
        migrations.RunPython(_migrate_json_list, _reverse),
        migrations.RunPython(_migrate_outfit_bundles, _reverse),
        migrations.RunPython(_migrate_marketplace_bundles, _reverse),
        migrations.RunPython(_migrate_wear_logs, _reverse),
    ]
