# Generated by Django 6.0.5 on 2026-05-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantProduct',
            fields=[
                ('product_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Top', 'Top'), ('Bottom', 'Bottom'), ('Footwear', 'Footwear'), ('Layer', 'Layer'), ('Accessory', 'Accessory')], max_length=50)),
                ('subcategory', models.CharField(max_length=100)),
                ('primary_color', models.CharField(max_length=100)),
                ('secondary_color', models.CharField(blank=True, max_length=100, null=True)),
                ('color_family', models.CharField(choices=[('Neutral', 'Neutral'), ('Earth', 'Earth'), ('Dark', 'Dark'), ('Bold', 'Bold'), ('Pastel', 'Pastel'), ('Warm', 'Warm')], max_length=50)),
                ('pattern', models.CharField(choices=[('Solid', 'Solid'), ('Stripes', 'Stripes'), ('Checks', 'Checks'), ('Graphic', 'Graphic'), ('Floral', 'Floral'), ('Abstract', 'Abstract')], max_length=50)),
                ('fit', models.CharField(choices=[('Slim', 'Slim'), ('Regular', 'Regular'), ('Relaxed', 'Relaxed'), ('Oversized', 'Oversized'), ('Cropped', 'Cropped'), ('Baggy', 'Baggy'), ('Tapered', 'Tapered')], max_length=50)),
                ('occasion_type', models.JSONField(default=list)),
                ('season', models.CharField(choices=[('Summer', 'Summer'), ('Winter', 'Winter'), ('Monsoon', 'Monsoon'), ('All-season', 'All-season')], max_length=50)),
                ('formality_level', models.IntegerField()),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('material', models.CharField(blank=True, max_length=100, null=True)),
                ('style_tags', models.JSONField(blank=True, null=True)),
                ('mood_tags', models.JSONField(blank=True, null=True)),
                ('aesthetic_tone', models.CharField(blank=True, max_length=255, null=True)),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
