# Generated by Django 6.0.5 on 2026-05-23 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bundle_generate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantproduct',
            name='sales_count',
            field=models.IntegerField(default=0),
        ),
    ]
