# Generated by Django 4.2.30 on 2026-07-29 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bundle_generate', '0004_bottomwearaigeneration'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopwearAiRecommendation',
            fields=[
                ('item_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Top', 'Top'), ('Bottom', 'Bottom'), ('Footwear', 'Footwear'), ('Layer', 'Layer'), ('Accessory', 'Accessory')], max_length=50)),
                ('subcategory', models.CharField(max_length=100)),
                ('primary_color', models.CharField(max_length=100)),
                ('secondary_color', models.CharField(blank=True, max_length=100, null=True)),
                ('color_family', models.CharField(choices=[('Neutral', 'Neutral'), ('Earth', 'Earth'), ('Dark', 'Dark'), ('Bold', 'Bold'), ('Pastel', 'Pastel'), ('Warm', 'Warm')], max_length=50)),
                ('pattern', models.CharField(choices=[('Solid', 'Solid'), ('Stripes', 'Stripes'), ('Checks', 'Checks'), ('Graphic', 'Graphic'), ('Floral', 'Floral'), ('Abstract', 'Abstract')], max_length=50)),
                ('fit', models.CharField(choices=[('Slim', 'Slim'), ('Regular', 'Regular'), ('Relaxed', 'Relaxed'), ('Oversized', 'Oversized'), ('Cropped', 'Cropped'), ('Baggy', 'Baggy'), ('Tapered', 'Tapered')], max_length=50)),
                ('occasion_type', models.JSONField(default=list)),
                ('season', models.CharField(choices=[('Summer', 'Summer'), ('Winter', 'Winter'), ('Monsoon', 'Monsoon'), ('All-season', 'All-season')], max_length=50)),
                ('formality_level', models.IntegerField()),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('material', models.CharField(blank=True, max_length=100, null=True)),
                ('style_tags', models.JSONField(blank=True, null=True)),
                ('mood_tags', models.JSONField(blank=True, null=True)),
                ('aesthetic_tone', models.CharField(blank=True, max_length=255, null=True)),
                ('wear_count', models.IntegerField(default=0)),
                ('last_worn', models.CharField(blank=True, max_length=100, null=True)),
                ('image_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('original_image', models.CharField(blank=True, max_length=1000, null=True)),
                ('processed_image', models.CharField(blank=True, max_length=1000, null=True)),
                ('product_url', models.CharField(blank=True, max_length=2000, null=True)),
                ('ai_generated', models.BooleanField(default=False)),
                ('fallback_used', models.BooleanField(default=False)),
                ('added_at', models.CharField(max_length=100)),
                ('user_id', models.IntegerField()),
            ],
        ),
    ]
