# Generated by Django 4.2.30 on 2026-08-19
# Data migration: migrate legacy flat occasion_type values to the
# hierarchical occasion taxonomy for the merchant/AI-catalog models.

from django.db import migrations

from services.occasion_taxonomy import normalize_occasion_list


def _migrate_occasion_type(apps, schema_editor):
    model_names = [
        'MerchantProduct',
        'FootwearAiRecommendation',
        'BottomwearAiGeneration',
        'TopwearAiRecommendation',
    ]
    for model_name in model_names:
        Model = apps.get_model('bundle_generate', model_name)
        for obj in Model.objects.all():
            mapped = normalize_occasion_list(obj.occasion_type or [])
            if mapped != obj.occasion_type:
                obj.occasion_type = mapped
                obj.save(update_fields=['occasion_type'])


def _reverse(apps, schema_editor):
    # Intentionally irreversible: mapping back from a hierarchy to flat
    # legacy tags would lose the new parent/child information.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('bundle_generate', '0005_topwearairecommendation'),
    ]

    operations = [
        migrations.RunPython(_migrate_occasion_type, _reverse),
    ]
