# Generated by Django 6.0.5 on 2026-05-23 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_onboardingquestion_user_full_name_user_is_onboarded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useronboardingresponse',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
